#!/bin/bash

# CRON Job script for automated backup
# Script which can be added in cron tab
directory="/home/ubuntu/dbs"
files=`find "$directory" -name "*.json"`

for x in $files
do
	python ${directory}/parse_json.py $x | ${directory}/db_backup_script
done